import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Container, Theme } from '@radix-ui/themes'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import AuthProvider from './api/auth/Provider'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.variable}>
          <Theme appearance="light" accentColor="yellow" grayColor="gray">
            <NavBar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </body>
      </AuthProvider>
    </html>
  )
}
